### ISSUE TITLE
error running plugin task

### ISSUE THREAD

**Issue by tctx79** [WithoutPants/stash-plugin-duplicate-finder#9]
I am getting "error running plugin task: /fork/exec /root/,stash/plugins/stash-plugin-duplicate-finder-win/plugin-duplicate-finder: no such file or directory"

I'm running stash in docker.
Volume is set up in config for /root/.stash and is accessible from cli from within docker.
Using the windows release un-tarred into the plugins folder.

**Comment by harlequinmarlin** [comment]
@tctx79 Did you find a solution?

**Comment by tctx79** [comment]
> @tctx79 Did you find a solution?

No I stopped using the program.

**Comment by harlequinmarlin** [comment]
> > @tctx79 Did you find a solution?
> 
> No I stopped using the program.

That's one way to fix the problem lol
